baseURL = 'https://fortrancon.org/'
languageCode = 'en-us'
title = 'FortranCon'
sectionPagesMenu = 'main'

[module]
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params]
[params.ananke.social.youtube]
  username = "fortrancon"

[params.ananke.social.follow]
new_window_icon = false
networks = [
  "youtube",
]
